### ISSUE TITLE
Quick Question: Must label all interested objects? 

### ISSUE THREAD

**Issue by LeonDong1993** [jinfagang/kitti-ssd#19]
When labeling our own dataset, for each image, are we MUST label all the objects in the images that we are interested ?

If object A is in the image but we do not label it, do this means you are telling the Neural Network, the region that object A lies is background. 
In other words, all the regions in the image that are not labelled is treated as class 'Background' ?

**Comment by LeonDong1993** [comment]
@jinfagang  Hope you can help me out.

**Comment by lucasjinreal** [comment]
@LeonDong1993 Definitely..... all classes should be labeled otherwise it suppose to be background

**Comment by LeonDong1993** [comment]
@jinfagang  Thank you so much, you are so nice !

Just one more question, if I have m ground truth box and the NN give n predicted box. How to evaluate the accuracy in this case ? 
I know IoU is used to evaluate the precision between two boxes. But how when there are multiple true and predicted box?

**Comment by LeonDong1993** [comment]
I have figured it out! Thanks !
