### ISSUE TITLE
should I install caffe and ssd_caffe first?

### ISSUE THREAD

**Issue by albertyou2** [jinfagang/kitti-ssd#2]
hi @jinfagang  Great work!

I am wandering if I NEED to install ssd_caffe and caffe first?

thank you

**Comment by lucasjinreal** [comment]
Should install ssd_caffe.

**Comment by albertyou2** [comment]
HI @jinfagang
thanks for help! 
now I am  downloading caffe Vgg model for ssd , but I do not know which one is the so called 'place-vgg-v2-caffemodel-here '.

Do you mean this one : ' http://cs.unc.edu/~wliu/projects/ParseNet/VGG_ILSVRC_16_layers_fc_reduced.caffemodel'?
