### ISSUE TITLE
txt format

### ISSUE THREAD

**Issue by jundongchang** [jinfagang/kitti-ssd#5]
Hi the txt format you given as follow:
class_index xmin ymin xmax ymax

Is the column "class_index" numerical value? 

If a class "Car" which label value in labelmap.prototxt denoted as "1".

Should I put this object as follow like this:
1 50 49 80 125

**Comment by lucasjinreal** [comment]
Yeah, this is it.

**Comment by jundongchang** [comment]
It works, thanks!
